<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
    'Spam' => 'Спам',
    'Removed' => 'Удалённые',
    'Submitted' => 'Отправленные',
    'Inbox' => 'Входящие',
    'Write' => 'Написать',
    'Cancel' => 'Отмена',
    'Send' => 'Отправить',
    'This is spam!' => 'Это спам!',
    'Remove' => 'Удалить',
    'This user does not exist' => 'Такого пользователя не существует',
    'You can not send messages to yourself' => 'Нельзя отправлять сообщения самому себе',
    'Subject' => 'Тема',
    'Content' => 'Содержание',
    'Dispatch date' => 'Дата отправки',
    'Sender ID' => 'ID отправителя',
    'Recipient nickname' => 'Никнейм получателя',
    'Recipient ID' => 'ID получателя',
    'Marked by the recipient as "Spam"' => 'Помечено получателем, как "Спам"',
    'Read by the recipient' => 'Прочтено получателем',
    'Deleted sender' => 'Удалено отправителем',
    'Deleted recipient' => 'Удалено получателем',
    'Message sent successfully!' => 'Сообщение успешно отправлено!',
    'This message does not exist' => 'Такого сообщения не существует',
    'Fields with <span class="required">*</span> are required' => 'Поля, помеченные  <span class="required">*</span> обязательны для заполнения',
    'Yesterday at' => 'Вчера в',
    'Today at' => 'Сегодня в',
);
