<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
    'Spam' => '',
    'Removed' => '',
    'Submitted' => '',
    'Inbox' => '',
    'Write' => '',
    'Cancel' => '',
    'Send' => '',
    'This is spam!' => '',
    'Remove' => '',
    'This user does not exist' => '',
    'You can not send messages to yourself' => '',
    'Subject' => '',
    'Content' => '',
    'Dispatch date' => '',
    'Sender ID' => '',
    'Recipient nickname' => '',
    'Recipient ID' => '',
    'Marked by the recipient as "Spam"' => '',
    'Read by the recipient' => '',
    'Deleted sender' => '',
    'Deleted recipient' => '',
    'Message sent successfully!' => '',
    'This message does not exist' => '',
    'Fields with <span class="required">*</span> are required' => '',
    'Yesterday at' => '',
    'Today at' => '',
);
